---
title: "Abstract"
---

# Pattern Submodels: why you could use them and what we don't know yet?

## NIHR Stats conference

Missing data is the scourge of prediction models and mishandling of incomplete entries can lead to biased and/or unusable models.

Pattern submodels (PSM) are a method proposed by Fletcher Mercaldo and Blume (2020) which allows a predictive model to be built with datasets with substantial missing data with various missingness mechanisms and without imputation. For each 'pattern' of missing data (e.g., FEV1 is missing but all other predictors are present), a model is fitted but only with the data that has this missingness pattern (subject to some other constraints). This leads to 2\^p models being fitted (where p is the number of predictors being used). Furthermore, it is easy to make the models interpretable and transportable rather than the 'blackbox' of some machine learning techniques.

Currently, there has been very little work since that has developed PSMs, despite garnering some interest in their implementation (currently 43 citations in Scopus). While C statistics and calibration curves can be defined for these models, other methods, such as regularisation and shrinkage, to avoid overftting have yet to be developed and so far have caused major questions for these ensemble models. There continues to be questions about how generalisable the models would be if the reasons for missing data are not the same between development and in-the-wild testing.

As part of ICS-RECODE, we are using PSMs as a potential approach to handle data missingness within our study datasets. Maybe you could try PSMs for your next prediction model?
