project:
  type: website

website:
  title: "Seb's Notebook"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Studies"
        href: studies.qmd
      - section: "R Code"
        href: rcode.qmd
        contents: 
          - submodels.qmd
      - text: "To-do list"
        href: todolist.qmd
            
          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

