project:
  type: website
  render: 
    - "*.qmd"
    - "!comparison.qmd"

website:
  title: "Seb's Notebook"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Studies"
        href: studies.qmd
      - text: "Examples studies"
        href: example_studies.qmd
      - section: "R Code"
        href: rcode.qmd
        contents: 
          - text: "Submodels"
            href: submodels.qmd
          - text: "Helper Functions"
            href:  helper_functions.qmd
      - text: "Regression Imputation"
        href: ri.qmd
      - text: "Random Forests"
        href: rf.qmd
      - text: "Model Comparison"
        href: comparison.qmd
      - section: "C-for-benefit"
        href: c4b.qmd
        contents: 
          - text: "Applications of C4B"
            href: c4bwild.qmd
      - text: "Splines"
        href: splines.qmd
      - text: "Models progress"
        href: progress.qmd
      - text: "To-do list"
        href: todolist.qmd
            
csl: csl/harvard-cite-them-right.csl
  
format:
  html:
    theme: 
      dark: darkly
      light: darkly
    highlight-style: .theme/custom.theme
    css: styles.css
    toc: true

editor: visual

