project:
  type: website

website:
  title: "Seb's Notebook"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Studies"
        href: studies.qmd
      - text: "Examples studies"
        href: example_studies.qmd
      - section: "R Code"
        href: rcode.qmd
        contents: 
          - text: "Submodels"
            href: submodels.qmd
          - text: "Helper Functions"
            href:  helper_functions.qmd
      - text: "Random Forests"
        href: rf.qmd
      - text: "Splines"
        href: splines.qmd
      - text: "To-do list"
        href: todolist.qmd
            

  
format:
  html:
    theme: 
      dark: darkly
      light: darkly
    highlight-style: .theme/custom.theme
    css: styles.css
    toc: true

editor: visual

